#See: http://www.paulgraham.com/rootsoflisp.html
#support functions
lp:=(
rp:=)
space :=
space +=
expandl=$(subst $(lp), $(lp) ,$(1))
expandr=$(subst $(rp), $(rp) ,$(1))
expand=$(subst ( ),(),$(strip $(call expandr,$(call expandl,$(1)))))
contractl=$(subst $(lp)$(space),$(lp),$(1))
contractr=$(subst $(space)$(rp),$(rp),$(1))
contract=$(strip $(call contractr,$(call contractl,$(1))))
triml=$(wordlist 2,$(words $(1)),$(1))
trimr=$(wordlist 1,$(call numdec,$(1)),$(1))
trim=$(call trimr,$(call triml,$(1)))
numinc=$(words $(1) .)
numdec=$(words $(call triml,$(1)))
getlist=$(if $(1),$(if $(filter $(word $(words $(3) .),$(2)),$(rp)),$(call getlist,$(call triml,$(1)),$(2),$(3) .),$(if $(filter $(word $(words $(3) .),$(2)),$(lp)),$(call getlist,$(1) .,$(2),$(3) .),$(call getlist,$(1),$(2),$(3) .))),$(3))
#getarg1=$(if $(filter $(word 1,$(1)),$(lp)),$(wordlist 1,$(words $(call getlist,.,$(1),.)),$(1)),$(word 1,$(1)))
inxarg1=$(if $(filter $(word 1,$(1)),$(lp)),$(words $(call getlist,.,$(1),.)),1)
getarg1=$(wordlist 1,$(call inxarg1,$(1)),$(1))
inxarg2=$(if $(filter $(word 1,$(1)),$(lp)),$(call numinc,$(call getlist,.,$(1),.)),2)
getarg2=$(wordlist $(call inxarg2,$(1)),$(words $(1)),$(1))
getsubarg=$(if $(filter $(word 2,$(1)),$(lp)),$(wordlist 2,$(words $(call getlist,.,$(1),. .)),$(1)),$(word 2,$(1)))
inxsubarg1=$(words $(call getlist,.,$(1),. .))
getsubarg1=$(wordlist 2,$(call inxsubarg1,$(1)),$(1))
inxsubarg2=$(words $(call getlist,.,$(1),. .) .)
getsubarg2=$(wordlist $(call inxsubarg2,$(call getarg1,$(1))),$(call numdec,$(call getarg1,$(1))),$(1))
get1st=$(wordlist 1,$(words $(call getlist,.,$(1),.)),$(1))
gettail=$(wordlist $(call numinc, $(call getlist,.,$(1),.)),$(words $(1)),$(1))
streq=$(and $(filter $(1),$(2)),$(filter $(2),$(1)))
len=$(filter $(words $(2)),$(1))
#bootstrap eval for Sexpr
sevalparse=primitive:$(word 2,$(call expand,$(1))) arg:$(wordlist 3,$(call numdec,$(call expand,$(1))),$(call expand,$(1)))
seval=$(call $(word 2,$(call expand,$(1))),$(wordlist 3,$(call numdec,$(call expand,$(1))),$(call expand,$(1))))
#These are the 7 primitives implemented with make intrinsyc functions
quote=$(1)
atom=$(if $(call len,1,$(call seval,$(1))),t,())
eq=$(if $(and $(call len,1,$(call seval,$(call getarg1,$(1)))),$(call len,1,$(call seval,$(call getarg2,$(1))))),$(if $(call streq,$(call seval,$(call getarg1,$(1))),$(call seval,$(call getarg2,$(1)))),t,()),())
car=$(if $(filter $(word 2,$(call seval,$(1))),$(lp)),$(wordlist 2,$(words $(call getlist,.,$(call seval,$(1)),. .)),$(call seval,$(1))),$(word 2,$(call seval,$(1))))
cdr=$(lp) $(wordlist $(if $(filter $(word 2,$(call seval,$(1))),$(lp)),$(words $(call getlist,.,$(call seval,$(1)),. .) .),3),$(words $(call seval,$(1))),$(call seval,$(1)))
cons=$(lp) $(call seval,$(call getarg1,$(1))) $(call trim,$(call seval,$(call getarg2,$(1)))) $(rp)
condparse=subarg1:[$(call getsubarg1,$(1))],subarg2:[$(call getsubarg2,$(1))],tail:[$(call gettail,$(1))]
cond=$(if $(call streq,t,$(call seval,$(call getsubarg1,$(1)))),$(call seval,$(call getsubarg2,$(1))),$(call cond,$(call gettail,$(1))))
#Extra functions
null=$(call seval,(eq $(1) (quote ())))
andd=$(call seval,(cond ($(1) (cond ($(2) (quote t)) ((quote t) (quote ())))) ((quote t) (quote ()))))
nott=$(call seval,(cond ($(1) (quote ()))((quote t)(quote t))))
cadr=$(call seval,(car (cdr $(1))))
#append=$(call seval,(cond ((null $(1)) $(2)) ((quote t) (cons (car $(1)) $(call append,(cdr $(1)),$(2))))))
#
all:
	@printf "expand,(a b c)=$(call expand,(a b c))\n"
	@printf "subst ( ) to () =$(subst ( ),(),( ))\n"
	@printf "expand,(() a b c)=$(subst ( ),(),$(call expand,(() a b c)))\n"
	@printf "expand,(() a b c)=$(call expand,(() a b c))\n"
	@printf "expand ((a b)(c d))=$(call expand,((a b)(c d)))\n"
	@printf "streq,a,b=>$(call streq,a,b)<\n"
	@printf "streq,a,a=>$(call streq,a,a)<\n"
	@printf "streq,aaaa,aaab=>$(call streq,aaaa,aaab)<\n"
	@printf "streq,( a b ),( a b ) =>$(call streq,( a b ),( a b ))<\n"
	@printf "triml, ..=>$(call triml, . . )<\n"
	@printf "triml, .=>$(call triml, . )<\n"
	@printf "triml, ( a b )=>$(call triml, ( a b ) )<\n"
	@printf "trimr, ( a b )=>$(call trimr, ( a b ) )<\n"
	@printf "trim, ( a b )=>$(call trim, ( a b ) )<\n"
	@printf "numdec, . . .=>$(call numdec, . . .)<\n"
	@printf "getlist,.,( x ),.=>$(call getlist,.,( x ),.)<\n"
	@printf "getlist,., ( a b ),.=>$(call getlist,., ( a b ),.)<\n"
	@printf "getlist,.,( a b ( c ) d ) ( f g ),.=>$(call getlist,.,( a b ( c ) d ) e ( f g ) ,.)<\n"
	@printf "getlist,.,( (a b)(c d)) ),.=>$(call getlist,.,( ( a b ) ( c d ) ),.)<\n"
	@printf "inxarg1,a b=>$(call inxarg1,a b)<\n"
	@printf "inxarg1,(a b) c=>$(call inxarg1,( a b ) c)<\n"
	@printf "inxarg1,a (b c)=>$(call inxarg1,a ( b c ))<\n"
	@printf "inxarg1,(a b) (c d)=>$(call inxarg1,( a b ) ( c d ))<\n"
	@printf "inxarg2,a b=>$(call inxarg2,a b)<\n"
	@printf "inxarg2,(a b) c=>$(call inxarg2,( a b ) c)<\n"
	@printf "inxarg2,a (b c)=>$(call inxarg2,a ( b c ))<\n"
	@printf "inxarg2,(a b) (c d)=>$(call inxarg2,( a b ) ( c d ))<\n"
	@printf "(quote a)=>$(call seval,(quote a))<\n"
	@printf "(quote ())=>$(call seval,(quote ()))<\n"
	@printf "(quote (a b))=>$(call seval,(quote (a b)))<\n"
	@printf "(atom 'a)=>$(call seval,(atom (quote a)))<\n"
	@printf "(atom '())=>$(call seval,(atom (quote ())))<\n"
	@printf "(atom '(a b))=>$(call seval,(atom (quote (a b))))<\n"
	@printf "(eq 'a 'a) =>$(call seval,(eq (quote a) (quote a)))<\n"
	@printf "(eq 'a 'b) =>$(call seval,(eq (quote a) (quote b)))<\n"
	@printf "(eq 'atom 'atom) =>$(call seval,(eq (quote atom) (quote atom)))<\n"
	@printf "(eq '() '()) =>$(call seval,(eq (quote ()) (quote ())))<\n"
	@printf "(eq '(a b) '(a b)) =>$(call seval,(eq (quote (a b)) (quote (a b))))<\n"
	@printf "(car '((a b)(c d)))=>$(call seval,(car (quote ((a b)(c d)))))<\n"
	@printf "(car '(a))=$(call seval,(car (quote (a))))\n"
	@printf "(car '(a b c))=$(call seval,(car (quote (a b c))))\n"
	@printf "(car '(() b c))=$(call seval,(car (quote (() b c))))\n"
	@printf "(car '((a b)(c d))=$(call seval,(car (quote ((a b)(c d)))))\n"
	@printf "(atom (car '(a b)))=>$(call seval,(atom (car (quote (a b)))))<\n"
	@printf "(atom (car '((a b)(c d))))=>$(call seval,(atom (car (quote ((a b)(c d))))))<\n"
	@printf "(eq (car '(a b)) (car '(a b)))=>$(call seval,(eq (car (quote (a b))) (car (quote (a b)))))<\n"
	@printf "(eq (car '(a b)) (car '(c d)))=>$(call seval,(eq (car (quote (a b))) (car (quote (c d)))))<\n"
	@printf "(cdr '(a b))=$(call seval,(cdr (quote (a b))))\n"
	@printf "(cdr '((a b)(c d))=$(call seval,(cdr (quote ((a b)(c d)))))\n"
	@printf "(cdr '(a b ()))=$(call seval,(cdr (quote (a b ()))))\n"
	@printf "(cdr '(a ()))=$(call seval,(cdr (quote (a ()))))\n"
	@printf "(cadr '((a b) (c d)))=$(call seval,(cadr (quote ((a b) (c d)))))\n"
	@printf "(cons 'a '(b c))=$(call seval,(cons (quote a) (quote (b c))))\n"
	@printf "(cons 'a (cdr '(b c)))=$(call seval,(cons (quote a) (cdr (quote (b c)))))\n"
	@printf "(cons '(a b) '(c d))=$(call seval,(cons (quote (a b)) (quote (c d))))\n"
	@printf "(cons '() '(c d))=$(call seval,(cons (quote ()) (quote (c d))))\n"
	@printf "(cons '() '())=$(call seval,(cons (quote ()) (quote ())))\n"
	@printf "(getarg1 (f first)(t second))=$(call getarg1,$(call expand,(f first)(t second) ))\n"
	@printf "(gettail (f first)(t second))=$(call gettail,$(call expand,(f first)(t second) ))\n"
	@printf "(inxsubarg1 ((quote t) (quote first)))=$(call inxsubarg1,$(call expand,((quote t) (quote first))))\n"
	@printf "(condparse ('t 'first))=$(call seval,(condparse ((quote t) (quote first))))\n"
	@printf "(cond ('t 'first))=$(call seval,(cond ((quote t) (quote first))))\n"
	@printf "(condparse ('() 'first) ('t 'second))=$(call seval,(condparse ((quote ()) (quote first))((quote t)(quote second))))\n"
	@printf "(cond ('() 'first) ('t 'second))=$(call seval,(cond ((quote ()) (quote first))((quote t)(quote second))))\n"
	@printf "(cond ((eq 'a 'b) 'first)((atom 'a) 'second))=$(call seval,(cond ((eq (quote a) (quote b)) (quote first))((atom (quote a)) (quote second))))\n"
	@printf "(null (quote ()))=$(call seval,(null (quote ())))\n"
	@printf "(null (quote a))=$(call seval,(null (quote a)))\n"
	@printf "(nott (quote t))=$(call seval,(nott (quote t)))\n"
	@printf "(nott (quote ()))=$(call seval,(nott (quote ())))\n"
	@printf "(nott (quote ()))=$(call seval,(nott (quote ())))\n"
rest:
	@printf "(append (quote ())(quote (c d)))=$(call append,(quote ()),(quote (c d)))\n"
	@printf "(append (quote (a b))(quote (c d)))=$(call append,(quote (a b)),(quote (c d)))\n"
	@printf "(append (quote (a b))(quote (c d)))=$(call seval,(append (quote (a b))(quote (c d))))\n"
	@printf "(andd (quote t) (quote t))=$(call seval,(andd (quote t) (quote t)))\n"
